/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

import javax.swing.JFrame;

/**
 *
 * @author Chotika
 */
public class Hint_page extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Hint_page() {
        initComponents();
    }
    
    public static void main(String[] args) {
//        try{
//            UIManager.setLookAndFeel( new FlatMacLightLaf());
//        }
//        catch(Exception e){
//            System.err.println( "Failed to initialize LaF" );
//        }
        JFrame MainFrame = new JFrame();
        MainFrame.setContentPane(new Hint_page());
        
        MainFrame.setVisible(true);
        MainFrame.setSize(1200, 700);
        MainFrame.setLocationRelativeTo(null);
        MainFrame.setResizable(false);
        MainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Hint_ScrollPanel = new javax.swing.JPanel();
        DNA_hint = new javax.swing.JLabel();
        Finger_hint1 = new javax.swing.JLabel();
        Finger_hint2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(null);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Hint_ScrollPanel.setBackground(new java.awt.Color(47, 46, 62));
        Hint_ScrollPanel.setPreferredSize(new java.awt.Dimension(1185, 3440));
        Hint_ScrollPanel.setRequestFocusEnabled(false);
        Hint_ScrollPanel.setLayout(null);

        DNA_hint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/93.png"))); // NOI18N
        Hint_ScrollPanel.add(DNA_hint);
        DNA_hint.setBounds(0, 0, 1200, 700);

        Finger_hint1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/94.png"))); // NOI18N
        Hint_ScrollPanel.add(Finger_hint1);
        Finger_hint1.setBounds(0, 706, 1200, 566);

        Finger_hint2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/95.png"))); // NOI18N
        Hint_ScrollPanel.add(Finger_hint2);
        Finger_hint2.setBounds(0, 1278, 1200, 614);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/96.png"))); // NOI18N
        Hint_ScrollPanel.add(jLabel1);
        jLabel1.setBounds(0, 1898, 1200, 700);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/97.png"))); // NOI18N
        Hint_ScrollPanel.add(jLabel2);
        jLabel2.setBounds(0, 2604, 1200, 700);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Close");
        jButton1.setPreferredSize(new java.awt.Dimension(70, 32));
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Hint_ScrollPanel.add(jButton1);
        jButton1.setBounds(479, 3322, 187, 56);

        jScrollPane1.setViewportView(Hint_ScrollPanel);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1185, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DNA_hint;
    private javax.swing.JLabel Finger_hint1;
    private javax.swing.JLabel Finger_hint2;
    private javax.swing.JPanel Hint_ScrollPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
