/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

import javax.swing.JFrame;

/**
 *
 * @author Chotika
 */
public class Instruction extends javax.swing.JPanel {

    /**
     * Creates new form Instruction
     */
    public Instruction() {
        initComponents();
    }
    public static void main(String[] args) {
//        try{
//            UIManager.setLookAndFeel( new FlatMacLightLaf());
//        }
//        catch(Exception e){
//            System.err.println( "Failed to initialize LaF" );
//        }
        JFrame Instruct_Frame = new JFrame();
        Instruct_Frame.setContentPane(new Instruction());
        
        Instruct_Frame.setVisible(true);
        Instruct_Frame.setSize(1200, 700);
        Instruct_Frame.setLocationRelativeTo(null);
        Instruct_Frame.setResizable(false);
        Instruct_Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel1.setBackground(new java.awt.Color(47, 46, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(1185, 1300));
        jPanel1.setLayout(null);

        jButton1.setText("Back");
        jButton1.setToolTipText("");
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 1200, 140, 60);

        jButton2.setText("Next");
        jPanel1.add(jButton2);
        jButton2.setBounds(1000, 1190, 130, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/92.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 570, 1200, 700);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/91.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 591);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
