/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class P10chooseTestimony extends javax.swing.JPanel {
   private CardLayout cd;
    private JPanel mainPanel;
    /**
     * Creates new form StartPage1
     */
    public P10chooseTestimony(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        cd = (CardLayout) mainPanel.getLayout();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBT = new javax.swing.JButton();
        chosseT1BT = new javax.swing.JButton();
        chooseT2BT = new javax.swing.JButton();
        chooseT3BT = new javax.swing.JButton();
        fileLB = new javax.swing.JLabel();
        coin = new javax.swing.JLabel();
        coinLB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(null);

        backBT.setBackground(new java.awt.Color(242, 242, 242));
        backBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        backBT.setText("Next >");
        backBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 5, new java.awt.Color(174, 0, 0)));
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        add(backBT);
        backBT.setBounds(1040, 610, 100, 40);

        chosseT1BT.setBackground(new java.awt.Color(242, 242, 242));
        chosseT1BT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        chosseT1BT.setText("CHOOSE");
        chosseT1BT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        chosseT1BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chosseT1BTActionPerformed(evt);
            }
        });
        add(chosseT1BT);
        chosseT1BT.setBounds(170, 560, 110, 40);

        chooseT2BT.setBackground(new java.awt.Color(242, 242, 242));
        chooseT2BT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        chooseT2BT.setText("CHOOSE");
        chooseT2BT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        chooseT2BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseT2BTActionPerformed(evt);
            }
        });
        add(chooseT2BT);
        chooseT2BT.setBounds(550, 560, 110, 40);

        chooseT3BT.setBackground(new java.awt.Color(242, 242, 242));
        chooseT3BT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        chooseT3BT.setText("CHOOSE");
        chooseT3BT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        chooseT3BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseT3BTActionPerformed(evt);
            }
        });
        add(chooseT3BT);
        chooseT3BT.setBounds(940, 560, 110, 40);

        fileLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/filebg.png"))); // NOI18N
        add(fileLB);
        fileLB.setBounds(1000, 20, 70, 70);

        coin.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        coin.setText("   3");
        coin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(coin);
        coin.setBounds(1100, 40, 50, 20);

        coinLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/coin.png"))); // NOI18N
        add(coinLB);
        coinLB.setBounds(1090, 20, 60, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/chooseTestimony.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBTActionPerformed

    private void chosseT1BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chosseT1BTActionPerformed
        cd.show(mainPanel, "choose1");
    }//GEN-LAST:event_chosseT1BTActionPerformed

    private void chooseT2BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseT2BTActionPerformed
        cd.show(mainPanel, "choose2");
    }//GEN-LAST:event_chooseT2BTActionPerformed

    private void chooseT3BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseT3BTActionPerformed
        cd.show(mainPanel, "choose3");
    }//GEN-LAST:event_chooseT3BTActionPerformed
    /* testing panel*/
//    public static void main(String[] args){
//    JFrame f = new JFrame();
//    f.setContentPane(new P10chooseTestimony());
//    f.setSize(1200,700);
//    f.setResizable(false);
//    f.setLocationRelativeTo(null);
//    f.setVisible(true);
//    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBT;
    private javax.swing.JButton chooseT2BT;
    private javax.swing.JButton chooseT3BT;
    private javax.swing.JButton chosseT1BT;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinLB;
    private javax.swing.JLabel fileLB;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
