/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class P11_1_1chooseFingerEvi extends javax.swing.JPanel {

    /**
     * Creates new form chooseFingerEvi
     */
    public P11_1_1chooseFingerEvi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        liquorBT = new javax.swing.JButton();
        plateBT = new javax.swing.JButton();
        spoonBT = new javax.swing.JButton();
        potBT = new javax.swing.JButton();
        waterBT = new javax.swing.JButton();
        boxBT = new javax.swing.JButton();
        coin = new javax.swing.JLabel();
        coinLB = new javax.swing.JLabel();
        toolLB = new javax.swing.JLabel();
        fileLB1 = new javax.swing.JLabel();
        boxLB = new javax.swing.JLabel();
        plateLB = new javax.swing.JLabel();
        medbottleLB = new javax.swing.JLabel();
        water = new javax.swing.JLabel();
        liquorLB = new javax.swing.JLabel();
        spoonLB = new javax.swing.JLabel();
        wineBT1 = new javax.swing.JButton();
        wineLB1 = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();
        navybg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(null);

        liquorBT.setBackground(new java.awt.Color(242, 242, 242));
        liquorBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        liquorBT.setText("CHOOSE");
        liquorBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        liquorBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquorBTActionPerformed(evt);
            }
        });
        add(liquorBT);
        liquorBT.setBounds(100, 500, 110, 40);

        plateBT.setBackground(new java.awt.Color(242, 242, 242));
        plateBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        plateBT.setText("CHOOSE");
        plateBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        plateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateBTActionPerformed(evt);
            }
        });
        add(plateBT);
        plateBT.setBounds(700, 500, 110, 40);

        spoonBT.setBackground(new java.awt.Color(242, 242, 242));
        spoonBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        spoonBT.setText("CHOOSE");
        spoonBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        spoonBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spoonBTActionPerformed(evt);
            }
        });
        add(spoonBT);
        spoonBT.setBounds(540, 240, 110, 40);

        potBT.setBackground(new java.awt.Color(242, 242, 242));
        potBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        potBT.setText("CHOOSE");
        potBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        potBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potBTActionPerformed(evt);
            }
        });
        add(potBT);
        potBT.setBounds(1000, 500, 110, 40);

        waterBT.setBackground(new java.awt.Color(242, 242, 242));
        waterBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        waterBT.setText("CHOOSE");
        waterBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        waterBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterBTActionPerformed(evt);
            }
        });
        add(waterBT);
        waterBT.setBounds(370, 500, 110, 40);

        boxBT.setBackground(new java.awt.Color(242, 242, 242));
        boxBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        boxBT.setText("CHOOSE");
        boxBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        boxBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBTActionPerformed(evt);
            }
        });
        add(boxBT);
        boxBT.setBounds(860, 240, 110, 40);

        coin.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        coin.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        coin.setText("   3");
        coin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        coin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(coin);
        coin.setBounds(1110, 40, 50, 20);

        coinLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/coin.png"))); // NOI18N
        add(coinLB);
        coinLB.setBounds(1100, 20, 63, 63);

        toolLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/hint.png"))); // NOI18N
        add(toolLB);
        toolLB.setBounds(980, 10, 70, 80);

        fileLB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/filebg.png"))); // NOI18N
        add(fileLB1);
        fileLB1.setBounds(1040, 20, 70, 70);

        boxLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/box.png"))); // NOI18N
        add(boxLB);
        boxLB.setBounds(800, 70, 213, 213);

        plateLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/plate.png"))); // NOI18N
        add(plateLB);
        plateLB.setBounds(650, 300, 200, 200);
        plateLB.getAccessibleContext().setAccessibleDescription("");

        medbottleLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/medicinebottle.png"))); // NOI18N
        add(medbottleLB);
        medbottleLB.setBounds(960, 300, 200, 200);

        water.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/water.png"))); // NOI18N
        add(water);
        water.setBounds(330, 330, 170, 150);

        liquorLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/liquor.png"))); // NOI18N
        add(liquorLB);
        liquorLB.setBounds(50, 300, 200, 200);

        spoonLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/spoon.png"))); // NOI18N
        add(spoonLB);
        spoonLB.setBounds(480, 70, 210, 200);

        wineBT1.setBackground(new java.awt.Color(242, 242, 242));
        wineBT1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        wineBT1.setText("CHOOSE");
        wineBT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        wineBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineBT1ActionPerformed(evt);
            }
        });
        add(wineBT1);
        wineBT1.setBounds(210, 240, 110, 40);

        wineLB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/wine.png"))); // NOI18N
        add(wineLB1);
        wineLB1.setBounds(170, 40, 200, 200);

        backBT.setBackground(new java.awt.Color(242, 242, 242));
        backBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        backBT.setText("< Back");
        backBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 4, 0, new java.awt.Color(174, 0, 0)));
        add(backBT);
        backBT.setBounds(100, 590, 100, 40);

        navybg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/navybg.jpg"))); // NOI18N
        navybg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(navybg);
        navybg.setBounds(10, -10, 1200, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void liquorBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liquorBTActionPerformed

    }//GEN-LAST:event_liquorBTActionPerformed

    private void plateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateBTActionPerformed

    }//GEN-LAST:event_plateBTActionPerformed

    private void spoonBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spoonBTActionPerformed

    }//GEN-LAST:event_spoonBTActionPerformed

    private void potBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potBTActionPerformed

    }//GEN-LAST:event_potBTActionPerformed

    private void waterBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterBTActionPerformed

    }//GEN-LAST:event_waterBTActionPerformed

    private void boxBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBTActionPerformed

    }//GEN-LAST:event_boxBTActionPerformed

    private void wineBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineBT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wineBT1ActionPerformed
   /* testing panel*/
    public static void main(String[] args){
        JFrame f = new JFrame();
        f.setContentPane(new P11_1_1chooseFingerEvi());
        f.setSize(1200,700);
        f.setResizable(false);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBT;
    private javax.swing.JButton boxBT;
    private javax.swing.JLabel boxLB;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinLB;
    private javax.swing.JLabel fileLB1;
    private javax.swing.JButton liquorBT;
    private javax.swing.JLabel liquorLB;
    private javax.swing.JLabel medbottleLB;
    private javax.swing.JLabel navybg;
    private javax.swing.JButton plateBT;
    private javax.swing.JLabel plateLB;
    private javax.swing.JButton potBT;
    private javax.swing.JButton spoonBT;
    private javax.swing.JLabel spoonLB;
    private javax.swing.JLabel toolLB;
    private javax.swing.JLabel water;
    private javax.swing.JButton waterBT;
    private javax.swing.JButton wineBT1;
    private javax.swing.JLabel wineLB1;
    // End of variables declaration//GEN-END:variables
}
