/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

/**
 *
 * @author Khao
 */
public class P12ChooseSuspect extends javax.swing.JPanel {

    /**
     * Creates new form P12ChooseSuspect
     */
    public P12ChooseSuspect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choosePoppyBT = new javax.swing.JToggleButton();
        chooseDesmondBT = new javax.swing.JToggleButton();
        chooseAmiBT = new javax.swing.JToggleButton();
        fileLB = new javax.swing.JLabel();
        coin = new javax.swing.JLabel();
        coinLB = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(null);

        choosePoppyBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        choosePoppyBT.setText("CHOOSE");
        choosePoppyBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        add(choosePoppyBT);
        choosePoppyBT.setBounds(540, 540, 110, 40);

        chooseDesmondBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        chooseDesmondBT.setText("CHOOSE");
        chooseDesmondBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        chooseDesmondBT.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                chooseDesmondBTComponentAdded(evt);
            }
        });
        add(chooseDesmondBT);
        chooseDesmondBT.setBounds(900, 540, 110, 40);

        chooseAmiBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        chooseAmiBT.setText("CHOOSE");
        chooseAmiBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        add(chooseAmiBT);
        chooseAmiBT.setBounds(180, 530, 110, 40);

        fileLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/filebg.png"))); // NOI18N
        add(fileLB);
        fileLB.setBounds(1000, 20, 70, 70);

        coin.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        coin.setText("   3");
        coin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(coin);
        coin.setBounds(1100, 40, 50, 20);

        coinLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/coin.png"))); // NOI18N
        add(coinLB);
        coinLB.setBounds(1090, 20, 60, 60);

        backBT.setBackground(new java.awt.Color(242, 242, 242));
        backBT.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        backBT.setText("Confirm");
        backBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 5, new java.awt.Color(174, 0, 0)));
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        add(backBT);
        backBT.setBounds(1030, 620, 130, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/chooseSuspect.jpg"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBTActionPerformed

    private void chooseDesmondBTComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_chooseDesmondBTComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseDesmondBTComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBT;
    private javax.swing.JToggleButton chooseAmiBT;
    private javax.swing.JToggleButton chooseDesmondBT;
    private javax.swing.JToggleButton choosePoppyBT;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinLB;
    private javax.swing.JLabel fileLB;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
