/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Chotika
 */
public class P4_4Instruction extends javax.swing.JPanel {
   private CardLayout cd;
    private JPanel mainPanel;
    /**
     * Creates new form StartPage1
     */
    public P4_4Instruction(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        cd = (CardLayout) mainPanel.getLayout();
        initComponents();
    }
//    public static void main(String[] args) {
////        try{
////            UIManager.setLookAndFeel( new FlatMacLightLaf());
////        }
////        catch(Exception e){
////            System.err.println( "Failed to initialize LaF" );
////        }
//        JFrame Instruct_Frame = new JFrame();
//        Instruct_Frame.setContentPane(new P4_4Instruction());
//        
//        Instruct_Frame.setVisible(true);
//        Instruct_Frame.setSize(1200, 700);
//        Instruct_Frame.setLocationRelativeTo(null);
//        Instruct_Frame.setResizable(false);
//        Instruct_Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        backBT = new javax.swing.JButton();
        nextBT = new javax.swing.JButton();
        inst_2 = new javax.swing.JLabel();
        inst_1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));

        jPanel1.setBackground(new java.awt.Color(47, 46, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(1185, 1300));
        jPanel1.setLayout(null);

        backBT.setText("Back");
        backBT.setToolTipText("");
        backBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBTMouseClicked(evt);
            }
        });
        jPanel1.add(backBT);
        backBT.setBounds(90, 1200, 140, 60);

        nextBT.setText("Next");
        nextBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBTMouseClicked(evt);
            }
        });
        jPanel1.add(nextBT);
        nextBT.setBounds(1000, 1190, 130, 60);

        inst_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/Instruct_2.png"))); // NOI18N
        jPanel1.add(inst_2);
        inst_2.setBounds(0, 570, 1200, 700);

        inst_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/Instruct_1.png"))); // NOI18N
        jPanel1.add(inst_1);
        inst_1.setBounds(0, 0, 1200, 591);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBTMouseClicked
        // TODO add your handling code here:
        cd.show(mainPanel, "informationRicko");
    }//GEN-LAST:event_backBTMouseClicked

    private void nextBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBTMouseClicked
        // TODO add your handling code here:
        cd.show(mainPanel, "testbg");
    }//GEN-LAST:event_nextBTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBT;
    private javax.swing.JLabel inst_1;
    private javax.swing.JLabel inst_2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBT;
    // End of variables declaration//GEN-END:variables
}
