/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

import javax.swing.JFrame;

/**
 *
 * @author Chotika
 */
public class P_Menu_icon extends javax.swing.JPanel {

    /**
     * Creates new form Menu_icon
     */
    public P_Menu_icon() {
        initComponents();
    }
    public static void main(String[] args) {
        JFrame jFrame = new JFrame();
        jFrame.setContentPane(new P_Menu_icon());
        
        jFrame.setVisible(true);
        jFrame.setSize(1200, 700);
        jFrame.setLocationRelativeTo(null);
        jFrame.setResizable(false);
        jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b_exit = new javax.swing.JLabel();
        base_img = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/file_icon.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(470, 290, 250, 250);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/evidence_icon.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(820, 310, 250, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/timeline_icon.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(130, 290, 250, 250);

        b_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/exit_icon.png"))); // NOI18N
        add(b_exit);
        b_exit.setBounds(1070, 40, 80, 80);

        base_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/menubase.jpg"))); // NOI18N
        add(base_img);
        base_img.setBounds(0, 0, 1200, 700);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_exit;
    private javax.swing.JLabel base_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
